version: "3.1"


services:
  product-database:
    image: mysql
  #  command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: productDatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
#    volumes:
#      - ./databases/product/:/var/lib/mysql

#  eureka-server:
#    build: eureka-server/
#    restart: always
#    ports:
#      - 8761:8761
#
#  gateway:
#    build: gateway/
#    restart: always
#    ports:
#      - 8762:8762
#    links:
#      - eureka-server

  product-service:
    build: product-service/
    restart: always
    ports:
      - 8089:8089
    links:
#      - gateway
      - product-database
