eureka:
  port: 8761
  address: localhost
---
spring:
  profiles: docker
eureka:
  port: 8761
  address: eureka-server
---
server:
  port: 8762
  address: localhost

cart-service:
  id: CARTSERVICE
product-service:
  id: PRODUCTSERVICE
order-service:
  id: ORDERSERVICE

spring:
  application:
    name: zuul-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.address}:${eureka.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}

zuule:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
  routes:
    cart-service:
      path: /api/cart/**
      serviceId: ${cart-service.id}
      stripPrefix: false
    product-service:
      path: /api/products/**
      serviceId: ${product-service.id}
      stripPrefix: false
    order-service:
      path: /api/orders/**
      serviceId: ${order-service.id}
      stripPrefix: false



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
