server:
  port: 8081
  adress: localhost
#
#Spring
#
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/orderDatabase?useUnicode=true&serverTimezone=UTC
    driver: com.mysql.Driver
    username: root
    password:
    #initialization-mode: always
  jpa:
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        dialect: org.hibernate.dialect.MySQLDialec
        ddl-auto: update
        show-sql: false
        cache:
          use_query_cache: false
          use_second_level_cache: false
  http:
    multipart:
      max-file-size: 1500KB
      max-request-size: 1500KB
  main:
    allow-bean-definition-overriding: true


#
#EUREKA SETTINGS
#
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      defaultZone: http://localhost:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}
#
#FEING
#
feign:
  hystrix:
    enabled: true

product-service:
  name: PRODUCT-SERVICE
#product-availabillity-service:
#  name: PRODUCT-AVAILABILLITY-SEVICE
cart-service:
  name: CART-SERVICE
#
#Ribbon planning to make server load balancer to cart, product services
#
#Some setting here

#
#Hystrix
#
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000
      #After 3 failed request we turn on a default realisation,
      #after 1 min we will try again sent request to service
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 60000
      fallback:
        enable: true
        isolation:
          semaphore:
            maxConcurrentRequests: 3
