server:
  port: 8088
  adress: localhost
#
#Spring
#
spring:
  application:
    name: PRODUCT-AVAILABILLITY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/productDatabase?useUnicode=true&serverTimezone=UTC
    driver: com.mysql.Driver
    username: root
    password:
    #initialization-mode: always
  jpa:
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        dialect: org.hibernate.dialect.MySQLDialec
        ddl-auto: update
        show-sql: false
        cache:
          use_query_cache: false
          use_second_level_cache: false
  http:
    multipart:
      max-file-size: 1500KB
      max-request-size: 1500KB
  main:
    allow-bean-definition-overriding: true


#
#EUREKA SETTINGS
#
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      defaultZone: http://localhost:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}application.yml
