server:
  port: 8089
  address: localhost
#
#Spring
#
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/productDatabase?useUnicode=true&serverTimezone=UTC
    driver: com.mysql.Driver
    username: root
    password: 123
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      cache:
        use_query_cache: false
        use_second_level_cache: false
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        dialect: org.hibernate.dialect.MySQLDialect

  http:
    multipart:
      max-file-size: 1500KB
      max-request-size: 1500KB
  main:
    allow-bean-definition-overriding: true

#
#JWT
#
jwt:
  header: Authentication
  # 60 * 60 * 24 = 86400
  expires_in: 86400
  secret: sgd34bwfAbfSBPpe0r8gwbg
  cookie: AUTH-TOKEN
#
#EUREKA SETTINGS
#
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      defaultZone: http://localhost:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}
#
#FEING
#
feign:
  hystrix:
    enabled: true

recommendation-service:
  name: RECOMMENDATION-SERVICE
product-availabillity-service:
  name: PRODUCT-AVAILABILLITY-SERVICE
review-service:
  name: REVIEW-SEVICE
#
#Ribbon planning to make server load balancer to review, recommendation, availability services
#
#Some setting here

#
#Hystrix
#
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000
      #After 3 failed request we turn on a default realisation,
      #after 1 min we will try again sent request to service
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 60000
      fallback:
        enable: true
        isolation:
          semaphore:
            maxConcurrentRequests: 3

api:
  rout: /api
  products:
    rout: ${api.rout}/products
    current:
      rout: ${api.products.rout}/{id}
  group:
    rout: ${api.rout}/groups
    current:
      rout: ${api.group.rout}/{id}
  groupVariant:
    rout: ${api.rout}/groupVariant
    current:
      rout: ${api.groupVariant.rout}/{id}
  review-service:
    rout: ${api.rout}/{product}/reviews
    current:
      rout: ${api.review-service.rout}/{id}
