server:
  port: 8761
  address: localhost
---
spring:
  profiles: docker
server:
  port: 8761
  address: eureka-server
---
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    maxThreadsForPeerReplication: 0
  healthcheck:
        enabled: true
  instance:
    hostname: ${server.address}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5


